<a href="https://colab.research.google.com/github/bee2020malaysia/iNeuronBeeMalaysia/blob/master/iNueron_Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a function to compute 5/0 and use try/except to catch the exceptions

In [1]:
try:
    x = 5/0
except:
    print("Error dividing by zero")

Error dividing by zero


Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. Hint: Subject,Verb and Object should be declared in the program as shown below. 

In [0]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

sentence_list = [(sub+" "+ vb + " "+ ob)for sub in subjects for vb in verbs for ob in objects]
for sentence in sentence_list:
  print (sentence)


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1. 

In [0]:
import numpy as np

In [0]:
x = np.array ([1,2,3,5])
N = 3
np.vander(x,N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [0]:
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [0]:
x = np.array([1,2,3,5])
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [0]:
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [0]:
np.linalg.det(np.vander(x))

48.00000000000003

In [0]:
(5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)

48